title: regr - Examples
description: >- # this means to ignore newlines until "baseurl:"
  Examples for regr.
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: minima

# highlight
highlighter: rouge
